---
#
# Configuration file for 'remote_execution' plugin
#

# Can be true, false, or http/https to enable just one of the protocols
:enabled: true

# Mode to function in. Determines the transport used
:mode: ssh
